minesweeper: main.c
	gcc -Wall -O3 -Werror -Wextra -Wshadow -Wpointer-arith -o minesweeper main.c

install:
	cp minesweeper /usr/bin
	chmod +x /usr/bin/minesweeper

uninstall:
	rm /usr/bin/minesweeper
