import os
import sys
print("ghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghostghost")
i = os.system("python3 ./ghost.py")
