# by minqwq, dont use this for illegal!
import random
areacode1 = random.randint(10, 50)
areacode2 = random.randint(1, 5)
areacode3 = random.randint(1, 7)
year = random.randint(1920, 2004)
month = random.randint(1, 12)
day = random.randint(1, 27)
sx = random.randint(1, 99)
sex = random.randint(1, 2)
rand = random.randint(1, 9)
print(areacode1)
print(areacode2)
print(areacode3)
print(year)
print(month)
print(day)
print(sx)
print(sex)
print(rand)
