import time

print("P", end="\r")
time.sleep(0.05)
print("PY", end="\r")
time.sleep(0.05)
print("PY ", end="\r")
time.sleep(0.05)
print("PY O", end="\r")
time.sleep(0.05)
print("PY OS", end="\r")
time.sleep(0.05)
print("PY OS ", end="\r")
time.sleep(0.05)
print("PY OS Im", end="\r")
time.sleep(0.05)
print("PY OS Imp", end="\r")
time.sleep(0.05)
print("PY OS Impr", end="\r")
time.sleep(0.05)
print("PY OS Impro", end="\r")
time.sleep(0.05)
print("PY OS Improv", end="\r")
time.sleep(0.05)
print("PY OS Improve", end="\r")
time.sleep(0.05)
print("PY OS Improved", end="\r")
time.sleep(0.5)
print("PY OS Improved_", end="\r")
time.sleep(0.5)
print("                ", end="\r")
print("PY OS Improved", end="\r")
time.sleep(0.5)
print("PY OS Improved_", end="\r")
time.sleep(0.5)
print("                ", end="\r")
print("PY OS Improved")
