# Last changed at 2025-05-21 by minqwq
splashes = [
                "Also try PY OS(original)! it's still alive.",
                "ciallo(ciao + hello)~",
                "Don't tell mibino i love her",
                "Do you have problem not in documents manual? you can open issue or email me! run \"about -s\" to show contact info.",
                "return 0;",
                "Copyright minqwq/pyos-improved 2024--2025!",
                "0x0d000721",
                "E! 5!",
                "code is easy, like python, you can see https://docs.python.org to learn from don't know anything",
                "/dev/pts/1",
                "BLYAT, SUKAAAAAAAAAAA, SUKAAAAAAAAAAAAAAAAAAAAAAAAAA!!!!!!!!!!!!",
                "baka",
                "dracula is not a story, its real!",
                "Also listen Team Shanghai Alice's music!",
                "Also listen Team Flandre Studio's music!",
                "so nanoka?(like this?)",
                "#!/usr/bin/bash",
                "a phone, a miracle.",
                "i believe you can do it.",
                "Also try Touhou Project!",
                "Also try Undertale!",
                "Also try Minecraft!",
                "con aux nul"
            ]
